#!/usr/bin/env python
import os
import sys

# We reuse the godot-cpp from MGAS to save space/time, as they are in the same repo.
# If standalone, we would use "godot-cpp/SConstruct"
env = SConscript("../../godot-cpp/SConstruct")

# For the reference:
# - godot-cpp is expected to be at the project root or handled via valid path
# - Here we assume the user has godot-cpp submodule in the root `godot-cpp` folder
# - If godot-cpp is not found, this will fail.

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/libmbt.{}.{}.framework/libmbt.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/libmbt{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
